### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [molpopgen/fwdpp#143]
I would like to point out that identifiers like “[`__DIPLOID_HH__`](https://github.com/molpopgen/fwdpp/blob/28e9fcec6fe551f8cd880cbf8c892ff2c7eca3d1/fwdpp/diploid.hh#L10 "Update candidate")” and “[`__FWDPP_SUGAR_GSL_TAGS_HPP__`](https://github.com/molpopgen/fwdpp/blob/0b165ee16ccf9bbd01f2d0d3ce80f0c06bf32177/fwdpp/sugar/gsl/tags.hpp#L3 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by molpopgen** [comment]
Closing b/c this is very low priority. The chances of a name clash are vanishingly small and there are other things to do with this project in the short term.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
