### ISSUE TITLE
Fitness function call incorrect for multi locus simulations

### ISSUE THREAD

**Issue by molpopgen** [molpopgen/fwdpp#34]
Line 406 of sample_diploid.tcc should also pass along gametes and mutations.

**Comment by vancleve** [comment]
Should I wait to push a new version to homebrew until this fix is released?

**Comment by molpopgen** [comment]
Yeah--my student and I are working on a fix.  There have been a few issues
with the 0.4.4 release.  Fortunately, they only affect the stuff we are
doing now, and not standard use cases.

**Comment by molpopgen** [comment]
Closed with release of 0.4.6
